server:
  port: 3355

spring:
  application:
    name: cloud-configclient #这个名称是入驻客户端的名称

eureka:
  client:
    register-with-eureka: true #表示将自己注册进EurekaServer, 默认为true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka



